@startuml
title Sequence Diagram: Auth (Register)
caption Auth Register (POST)

skinparam shadowing false
skinparam ParticipantPadding 18
skinparam BoxPadding 10
skinparam sequence {
  LifeLineBorderColor #6B6B6B
  LifeLineBackgroundColor #FFFFFF
  ParticipantBorderColor #6B6B6B
  ParticipantBackgroundColor #CFE2F3
  ActorBorderColor #6B6B6B
  ArrowColor #6B6B6B
}

actor Client as client
participant ":server" as server <<javaScript>>
participant ":auth" as authRouter <<router>>
participant ":auth" as authCtrl <<controllers>>
participant ":User" as userModel <<model>>
database ":users" as usersDB <<MongoDB>>

client -> server : req.post('/api/v1/auth/register')
activate server

server -> authRouter : app.use('/api/v1/auth', auth)
activate authRouter

authRouter -> authCtrl : register()
activate authCtrl

authCtrl -> userModel : create(name,tel,email,password,role)
activate userModel

userModel -> usersDB : UserSchema.insert()
activate usersDB
usersDB --> userModel : user
deactivate usersDB

userModel --> authCtrl : user
deactivate userModel

authCtrl -> authCtrl : sendTokenResponse()
authCtrl --> authRouter : response (201 Created)\nJWT token in cookie/body
deactivate authCtrl

authRouter --> server : response
deactivate authRouter

server --> client : response
deactivate server

@enduml
